query getPoll($pollId: ID!) {
  Poll(_id: $pollId) {
    id
    options
    postedBy {
      firstName
      lastName
    }
    voteOptions {
      text
      id
      votesCount
    }
    title
  }
}
